// Generated by CoffeeScript 1.7.1

/*
 * Command class
 * Run pulseaudio commands
 */

(function() {
  var Command;

  Command = (function() {
    function Command() {
      var PulseAudio;
      PulseAudio = require('pulseaudio');
      this.context = new PulseAudio({
        client: 'pulseaudio-multi-recorder'
      });
    }


    /*
     * List the active sinks
     * @param callback function to execute after the method finish,
     *   receive the context as argument.
     *   If no callback is provided, end the context.
     */

    Command.prototype.list_sinks = function(callback) {
      var context;
      context = this.context;
      context.on('connection', function() {
        return context.sink(function(list) {
          console.log(list);
          if (callback == null) {
            return context.end();
          }
        });
      });
      return this;
    };

    return Command;

  })();

  module.exports = new Command();

}).call(this);
